-- ++ DELETING TABLE++
DROP TABLE IF EXISTS Usr CASCADE;
DROP TABLE IF EXISTS Tweet CASCADE;
DROP TABLE IF EXISTS Reshare CASCADE ;
DROP TABLE IF EXISTS Media CASCADE;
DROP TABLE IF EXISTS Cmmnt CASCADE;
DROP TABLE IF EXISTS Follow CASCADE;

